"""Storage interface.

The shape here encodes the project's main structural decision: **documents and chunks
are stored once; vectors are stored per space.** A corpus can therefore exist in several
embedding spaces simultaneously, which is what makes a zero-downtime migration possible
at all. If vectors and text were stored together, migrating would mean duplicating the
corpus, and rolling back would mean having kept the old copy.

`chunk_ids_missing_in` is the other load-bearing method: it makes backfill resumable.
A migration that dies halfway through restarts from where it stopped instead of from
the beginning, which matters when the corpus is large and embedding is the slow part.
"""

from __future__ import annotations

from typing import Protocol

from ..models import Chunk, Document, Vector


class VectorStore(Protocol):
    # --- corpus, shared across all spaces -------------------------------------- #
    def put_document(self, doc: Document) -> None: ...
    def get_document(self, doc_id: str) -> Document | None: ...
    def put_chunks(self, chunks: list[Chunk]) -> None: ...
    def get_chunk(self, chunk_id: str) -> Chunk | None: ...
    def all_chunk_ids(self) -> list[str]: ...
    def document_count(self) -> int: ...
    def chunk_count(self) -> int: ...

    # --- vectors, scoped to one space ------------------------------------------ #
    def put_vectors(self, vectors: list[Vector]) -> None: ...
    def vector_count(self, space_id: str) -> int: ...
    def candidates(self, space_id: str) -> list[tuple[str, list[float]]]: ...
    def chunk_ids_missing_in(self, space_id: str, limit: int | None = None) -> list[str]: ...
    def drop_space(self, space_id: str) -> int: ...
